#!/bin/bash

#
# Configure OS X
#

# Use Google DNS
networksetup -setdnsservers Wi-Fi 8.8.8.8 8.8.4.4
# Stop iTunes from launching when the Play/Pause button is pressed
launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist 2> /dev/null
# Disable OS X spelling correction
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
# Reduce use of transparency in OS X
# defaults write com.apple.universalaccess reduceTransparency -bool true
# Hide all desktop icons
defaults write com.apple.finder CreateDesktop -bool false
defaults write com.apple.screencapture location ~/Library/Mobile\ Documents/com\~apple\~CloudDocs/Screenshots/
# Show path bar in Finder
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true; killall Finder
# Show full posix path in Finder window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true
# Show file name extensions in Finder
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

git config --global core.editor

# Install homebrew
if [ ! -d "/opt/homebrew" ]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
# Install x86 homebrew
if [ ! -d "/usr/local/Cellar" ]; then
  arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

#
# Setup zsh
#

# Set zsh as the default shell
chsh -s /bin/zsh
# Install Oh My Zsh
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

#
# Install vim plugins
#

# Borrowed from https://robots.thoughtbot.com/rcm-for-rc-files-in-dotfiles-repos
if [ -e $HOME/.vim/bundle/Vundle.vim ]; then
  pushd $HOME/.vim/bundle/Vundle.vim
  git pull origin master
  popd
else
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi
vim +PluginInstall +qall

#
# Install RVM
#

brew install gpg
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
\curl -sSL https://get.rvm.io | bash -s stable

# Install Node LTS
brew install node@16
brew link node@16

# Install Qwandry
# gem install qwandry

brew bundle --file=~/repos/dotfiles/Brewfile
