#!/bin/bash

#
# Configure MacOS
#

touch ~/.hushlogin

# Use Google DNS
networksetup -setdnsservers Wi-Fi 8.8.8.8 8.8.4.4
# Change Dock icon size
defaults write com.apple.dock tilesize -int 48; killall Dock
# Stop iTunes from launching when the Play/Pause button is pressed
launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist 2> /dev/null
# Disable OS X spelling correction
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
# Reduce use of transparency
# defaults write com.apple.universalaccess reduceTransparency -bool true
# Hide all desktop icons
defaults write com.apple.finder CreateDesktop -bool false
defaults write com.apple.screencapture location ~/Library/Mobile\ Documents/com\~apple\~CloudDocs/Screenshots/
# Show path bar in Finder
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true; killall Finder
# Show full posix path in Finder window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true
# Show file name extensions in Finder
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

git config --global core.editor

# # Install homebrew
# if [ ! -d "/opt/homebrew" ]; then
#   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# fi
# Install x86 homebrew
if [ ! -d "/usr/local/Cellar" ]; then
  arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Set zsh as the default shell
chsh -s /bin/zsh
# # Install Oh My Zsh
# git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
# # Install zsh yarn completions plugin
# git clone https://github.com/chrisands/zsh-yarn-completions ~/.oh-my-zsh/custom/plugins/zsh-yarn-completions
# Install powerlevel10k zsh theme
brew tap "romkatv/powerlevel10k"
brew install "powerlevel10k"

# Install vim plugins
# Borrowed from https://robots.thoughtbot.com/rcm-for-rc-files-in-dotfiles-repos
if [ -e $HOME/.vim/bundle/Vundle.vim ]; then
  pushd $HOME/.vim/bundle/Vundle.vim
  git pull origin master
  popd
else
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi
vim +PluginInstall +qall

# Install Qwandry
# gem install qwandry

# Install software
brew bundle --file=~/repos/dotfiles/Brewfile
